### ISSUE TITLE
Characterizations reports failed

### ISSUE THREAD

**Issue by anemniugin** [OHDSI/Atlas#1625]
Desigh Characterization Cohort
[NPE_cc.txt](https://github.com/OHDSI/Atlas/files/3023380/NPE_cc.txt)

### Expected behavior
Can see report

### Actual behavior
Can see Failed report with 
`java.lang.NullPointerException: Null key.
	at org.json.JSONObject.put(JSONObject.java:1289)
	at org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet$CcTask.lambda$buildSettings$21(GenerateCohortCharacterizationTasklet.java:565)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet$CcTask.buildSettings(GenerateCohortCharacterizationTasklet.java:565)
	at org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet$CcTask.createFeJsonObject(GenerateCohortCharacterizationTasklet.java:553)
	at org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet$CcTask.getAnalysisQueriesOnCohort(GenerateCohortCharacterizationTasklet.java:172)
	at org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet$CcTask.lambda$run$0(GenerateCohortCharacterizationTasklet.java:164)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet$CcTask.run(GenerateCohortCharacterizationTasklet.java:166)
	at org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet$CcTask.access$000(GenerateCohortCharacterizationTasklet.java:127)
	at org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet.prepareStatementCreators(GenerateCohortCharacterizationTasklet.java:117)
	at org.ohdsi.webapi.common.generation.CancelableTasklet.doTask(CancelableTasklet.java:37)
	at org.ohdsi.webapi.common.generation.CancelableTasklet.doTask(CancelableTasklet.java:17)
	at org.ohdsi.webapi.common.generation.TransactionalTasklet.lambda$execute$0(TransactionalTasklet.java:37)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.ohdsi.webapi.common.generation.TransactionalTasklet.execute(TransactionalTasklet.java:37)
	at org.springframework.batch.core.s`

### Steps to reproduce behavior
Create Characterization
Import Cohort Definition "Aspirin users"
Import Feature Analyses "Feature analyses"

Go to Executions
Generate report(e.g. SynPUF 110k (GCP BigQuery)

**Comment by anemniugin** [comment]
retested
