### ISSUE TITLE
Characterizations: empty list of Executions

### ISSUE THREAD

**Issue by Andreyyiv** [OHDSI/Atlas#2147]
Atlas v2.7.6

### Expected behavior
Executions tab should have the list of Executions.

### Actual behavior
Executions tab is empty.

### Steps to reproduce behavior

1. Characterizations > New Characterization;
2. enter new characterization name;
3. click save;
4. go to Executions tab;
5. There is Executions header and nothing else.

I've noticed an interesting detail. This list is not always empty:

1. Characterizations > New Characterization;
2. enter new characterization name;
3. DO NOT click save;
4. go to Executions tab;
5. There is Execution header and a list of sources with "Generate" and other buttons.

I tried to specify the cohort and the feature analyses, go to the Executions tab, save the characterization, and then generate the characterization. All seem to work this way, the "Generate" button changes to "Pending" and then nothing happens. The job ("Generating cohort xxx") appears as COMPLETED in the top-level Jobs list, but it doesn't show up in the Executions list.

When the Executions tab is open, there are multiple calls to WebAPI/cohort-characterization/<id>/generation. The WebAPI log is below.

```
2020-03-09 16:31:15.880 DEBUG http-nio-8080-exec-5 org.springframework.jdbc.datasource.DriverManagerDataSource -  - Creating new JDBC DriverManager Connection to [jdbc:oracle:thin:@//server:port/db]
2020-03-09 16:31:15.925 WARN http-nio-8080-exec-5 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - SQL Error: 1722, SQLState: 42000
2020-03-09 16:31:15.925 ERROR http-nio-8080-exec-5 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - ORA-01722: invalid number

2020-03-09 16:31:15.928 ERROR http-nio-8080-exec-5 org.ohdsi.webapi.util.GenericExceptionMapper -  - javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1538)
        at org.hibernate.query.Query.getResultList(Query.java:165)
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:76)
        at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at com.cosium.spring.data.jpa.entity.graph.repository.support.RepositoryQueryEntityGraphInjector.invoke(RepositoryQueryEntityGraphInjector.java:48)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy270.getResultList(Unknown Source)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:125)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:89)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:128)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:118)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:494)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:477)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at com.cosium.spring.data.jpa.entity.graph.repository.support.RepositoryMethodEntityGraphExtractor$JpaEntityGraphMethodInterceptor.doInvoke(RepositoryMethodEntityGraphExtractor.java:157)
        at com.cosium.spring.data.jpa.entity.graph.repository.support.RepositoryMethodEntityGraphExtractor$JpaEntityGraphMethodInterceptor.invoke(RepositoryMethodEntityGraphExtractor.java:109)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy229.findByCohortCharacterizationIdOrderByIdDesc(Unknown Source)
        at org.ohdsi.webapi.cohortcharacterization.CcServiceImpl.findGenerationsByCcId(CcServiceImpl.java:470)
        at org.ohdsi.webapi.cohortcharacterization.CcServiceImpl$$FastClassBySpringCGLIB$$f0e45068.invoke(<generated>)
```

**Comment by Andreyyiv** [comment]
**Update.** The reason for `ORA-01722: invalid number` is the following statement (reduced):

```
SELECT *
FROM cc_generation v1
     LEFT OUTER JOIN cohort_characterization v2 ON v1.cc_id = v2.id
     LEFT OUTER JOIN source v3 ON v1.source_id = v3.source_id
WHERE v2.id = 10
ORDER BY v1.id DESC
;
```

The value `10` is a valid cohort characterization ID.
