### ISSUE TITLE
ENOENT: no such file or directory, open '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js' In module tree:

### ISSUE THREAD

**Issue by ssaranathan** [OHDSI/Atlas#2432]
### Expected behavior
 /usr/local/tomcat/webapps/atlas
RUN npm run build 
should build fine..
### Actual behavior

RUN npm run build
 ---> Running in d76bcc652e09

> atlas@2.8.0 build /usr/local/tomcat/webapps/atlas
> npm run prep && npm run build:dev

> atlas@2.8.0 prep /usr/local/tomcat/webapps/atlas
> npm i && npm run clean && npm run genversion

{ Error: Error: ENOENT: no such file or directory, open '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js'
In module tree:
    main
      pages/Router

    at Object.openSync (fs.js:448:3)

    at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28332:19
    at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3059:39
    at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2999:25
    at Function.prim.nextTick (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28083:9)
    at Object.errback (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2998:26)
    at Object.callback (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2984:23)
    at Object.then (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3038:23)
    at build (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28289:12)
    at runBuild (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:30302:17)
    at Object.execCb (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:1946:33)
  originalError:
   { Error: ENOENT: no such file or directory, open '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js'
       at Object.openSync (fs.js:448:3)
       at Object.readFileSync (fs.js:348:35)
       at Object.readFile (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3658:27)
       at Object.readFileAsync (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3672:32)
       at Function.require._cacheReadAsync (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28102:25)
       at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:27671:48
       at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:3041:37
       at /usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2989:25
       at Function.prim.nextTick (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:28083:9)
       at Object.callback (/usr/local/tomcat/webapps/atlas/node_modules/requirejs/bin/r.js:2988:26)
     errno: -2,
     syscall: 'open',
     code: 'ENOENT',
     path: '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js',
     fileName: '/usr/local/tomcat/webapps/atlas/node_modules/qs/dist/qs.js',
     moduleTree: [ 'pages/Router', 'main' ] } }

**Comment by chrisknoll** [comment]
The dist folder was removed from one of the releases of qs, but has since been restored in version 6.9.6.  Can you confirm that you have the proper version of QS?

**Comment by ssaranathan** [comment]
Hi @chrisknoll , thanks for the follow up.  Yes, I confirm that the build is working fine now .  Thanks,
